/**
 * Playwright Configuration for Stencil Component Library
 *
 * This example shows how to configure the component testing runtime
 * to work with a Stencil component library.
 *
 * Prerequisites:
 * 1. Build your Stencil components: `npm run build`
 * 2. Ensure dist/ contains the loader and ESM build
 * 3. Run tests: `npx playwright test`
 */

import { defineConfig, devices } from '@playwright/test';
import { withComponentTesting } from '@wc-tools/webrun';

export default withComponentTesting({
  /**
   * Port for the development server
   */
  port: 3000,

  /**
   * Directory containing your Stencil build output
   * This should match your stencil.config.ts outputTargets
   */
  staticDir: './dist',

  /**
   * Auto-start the web server (recommended for CI/CD)
   */
  autoStart: true,

  /**
   * Load the Stencil loader
   * This file is generated by Stencil and handles lazy loading of components
   *
   * Path structure:
   * - /build/my-component-library.esm.js (loader)
   * - /build/*.esm.js (component chunks)
   */
  scripts: [
    '/build/my-component-library.esm.js', // Replace with your library name
  ],

  /**
   * Optional: Load global styles
   */
  stylesheets: [
    '/build/my-component-library.css', // If you have global styles
  ],

  /**
   * Optional: Import map for external dependencies
   * Useful if your components import from CDN
   */
  importMap: {
    imports: {
      // Example: Map lit to CDN if you use Lit in Stencil
      // 'lit': 'https://cdn.jsdelivr.net/npm/lit@3/+esm'
    },
  },
})(
  defineConfig({
    testDir: './test',
    fullyParallel: true,

    /**
     * Test timeout (increase if components are slow to load)
     */
    timeout: 30000,

    use: {
      /**
       * Collect trace on first retry for debugging
       */
      trace: 'on-first-retry',

      /**
       * Take screenshot on failure
       */
      screenshot: 'only-on-failure',
    },

    /**
     * Test against multiple browsers
     */
    projects: [
      {
        name: 'chromium',
        use: { ...devices['Desktop Chrome'] },
      },
      {
        name: 'firefox',
        use: { ...devices['Desktop Firefox'] },
      },
      {
        name: 'webkit',
        use: { ...devices['Desktop Safari'] },
      },
    ],

    /**
     * Optional: Custom web server configuration
     * Uncomment to override the default http-server
     */
    // webServer: {
    //   command: 'npx vite preview --port 3000',
    //   port: 3000,
    //   reuseExistingServer: !process.env.CI,
    // },
  })
);
